import { Brain, Dumbbell, Utensils, TrendingUp, MessageSquare, Shield } from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Plans',
    description: 'Get personalized workout and nutrition plans generated by advanced AI based on your unique profile.',
    color: 'var(--color-primary)',
  },
  {
    icon: Dumbbell,
    title: 'Smart Workouts',
    description: 'Weekly workout schedules tailored to your goals with exercise recommendations and proper guidance.',
    color: 'var(--color-secondary)',
  },
  {
    icon: Utensils,
    title: 'Nutrition Guidance',
    description: 'Complete meal plans for breakfast, lunch, dinner, and snacks matching your dietary preferences.',
    color: 'var(--color-accent)',
  },
  {
    icon: MessageSquare,
    title: 'AI Coach Chat',
    description: 'Chat with your AI fitness coach anytime for exercise tips, diet advice, and motivation.',
    color: 'var(--color-success)',
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    description: 'Track weight, water intake, and workouts with beautiful charts to visualize your transformation.',
    color: 'var(--color-warning)',
  },
  {
    icon: Shield,
    title: 'Safe Plan Editing',
    description: 'Review AI-proposed plan changes side by side before approving — you stay in control.',
    color: 'var(--color-danger)',
  },
];

export default function Features() {
  return (
    <section id="features" className="relative py-24 md:py-32">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <span className="badge badge-primary text-xs uppercase tracking-wider mb-4 inline-block">Features</span>
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Everything You Need to
            <span className="gradient-text"> Transform</span>
          </h2>
          <p className="text-[var(--color-text-secondary)] max-w-2xl mx-auto">
            From AI-generated fitness plans to real-time coaching, FitGenie gives you all the tools
            to reach your fitness goals faster and smarter.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 stagger-children">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="glass-card p-8 group animate-fade-in-up"
              style={{ opacity: 0, animationFillMode: 'forwards' }}
            >
              <div
                className="w-14 h-14 rounded-2xl flex items-center justify-center mb-5 transition-transform group-hover:scale-110"
                style={{ background: `${feature.color}20` }}
              >
                <feature.icon size={26} style={{ color: feature.color }} />
              </div>
              <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
