'use client';

import { Brain, Dumbbell, Utensils, TrendingUp, MessageSquare, Shield } from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Plans',
    description: 'Get personalized workout and nutrition plans generated by advanced AI based on your unique profile.',
    gradient: 'linear-gradient(135deg, #5B8CFF 0%, #7B61FF 100%)',
    glow: 'rgba(91, 140, 255, 0.2)',
    border: 'rgba(91, 140, 255, 0.15)',
  },
  {
    icon: Dumbbell,
    title: 'Smart Workouts',
    description: 'Weekly workout schedules tailored to your goals with exercise recommendations and proper guidance.',
    gradient: 'linear-gradient(135deg, #22D3EE 0%, #5B8CFF 100%)',
    glow: 'rgba(34, 211, 238, 0.2)',
    border: 'rgba(34, 211, 238, 0.15)',
  },
  {
    icon: Utensils,
    title: 'Nutrition Guidance',
    description: 'Complete meal plans for breakfast, lunch, dinner, and snacks matching your dietary preferences.',
    gradient: 'linear-gradient(135deg, #A855F7 0%, #7B61FF 100%)',
    glow: 'rgba(168, 85, 247, 0.2)',
    border: 'rgba(168, 85, 247, 0.15)',
  },
  {
    icon: MessageSquare,
    title: 'AI Coach Chat',
    description: 'Chat with your AI fitness coach anytime for exercise tips, diet advice, and motivation.',
    gradient: 'linear-gradient(135deg, #22C55E 0%, #22D3EE 100%)',
    glow: 'rgba(34, 197, 94, 0.2)',
    border: 'rgba(34, 197, 94, 0.15)',
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    description: 'Track weight, water intake, and workouts with beautiful charts to visualize your transformation.',
    gradient: 'linear-gradient(135deg, #F59E0B 0%, #EF4444 100%)',
    glow: 'rgba(245, 158, 11, 0.2)',
    border: 'rgba(245, 158, 11, 0.15)',
  },
  {
    icon: Shield,
    title: 'Safe Plan Editing',
    description: 'Review AI-proposed plan changes side by side before approving — you stay in control.',
    gradient: 'linear-gradient(135deg, #EF4444 0%, #A855F7 100%)',
    glow: 'rgba(239, 68, 68, 0.2)',
    border: 'rgba(239, 68, 68, 0.15)',
  },
];

export default function Features() {
  return (
    <section id="features" className="relative py-28 md:py-36">
      {/* Subtle background */}
      <div className="absolute inset-0 bg-mesh opacity-20" />
      <div
        className="floating-orb floating-orb-purple"
        style={{ width: '500px', height: '500px', top: '50%', left: '50%', transform: 'translate(-50%,-50%)', opacity: 0.05, filter: 'blur(120px)' }}
      />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <div className="section-badge inline-flex mb-6">
            <Brain size={12} />
            Features
          </div>
          <h2 className="text-3xl md:text-5xl font-bold mb-5 tracking-tight">
            Everything You Need to
            <span
              style={{
                background: 'linear-gradient(135deg, #5B8CFF 0%, #7B61FF 50%, #22D3EE 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              {' '}Transform
            </span>
          </h2>
          <p className="text-lg max-w-2xl mx-auto" style={{ color: '#B8C0D4', lineHeight: '1.7' }}>
            From AI-generated fitness plans to real-time coaching, FitGenie gives you all the tools
            to reach your fitness goals faster and smarter.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 stagger-children">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="group animate-fade-in-up"
              style={{ opacity: 0, animationFillMode: 'forwards' }}
            >
              <div
                style={{
                  background: 'rgba(14, 20, 40, 0.6)',
                  backdropFilter: 'blur(20px)',
                  border: `1px solid ${feature.border}`,
                  borderRadius: '24px',
                  padding: '32px',
                  transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
                  cursor: 'default',
                  position: 'relative',
                  overflow: 'hidden',
                }}
                onMouseEnter={(e) => {
                  const el = e.currentTarget as HTMLElement;
                  el.style.transform = 'translateY(-6px)';
                  el.style.boxShadow = `0 20px 50px ${feature.glow}, 0 0 0 1px ${feature.border}`;
                }}
                onMouseLeave={(e) => {
                  const el = e.currentTarget as HTMLElement;
                  el.style.transform = '';
                  el.style.boxShadow = '';
                }}
              >
                {/* Top gradient line */}
                <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '1px', background: feature.gradient, opacity: 0.4 }} />

                {/* Icon */}
                <div
                  className="mb-5"
                  style={{
                    width: '52px',
                    height: '52px',
                    borderRadius: '16px',
                    background: feature.gradient,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    boxShadow: `0 8px 24px ${feature.glow}`,
                    transition: 'transform 0.3s',
                  }}
                >
                  <feature.icon size={24} className="text-white group-hover:scale-110 transition-transform" />
                </div>

                <h3 className="text-lg font-bold mb-3 tracking-tight" style={{ color: '#FFFFFF' }}>
                  {feature.title}
                </h3>
                <p className="text-sm leading-relaxed" style={{ color: '#B8C0D4' }}>
                  {feature.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
